#Deploy 2
stages:
  - build
  - unit_test
  - update_helm_chart

variables:
  APP_NAME: webcongress-test-delivery
  IMAGE_TAG: registry.gitlab.com/devdevrl/webcongress-test-delivery/$APP_NAME:$CI_COMMIT_SHORT_SHA

build_image:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - echo "Image built"

test:
  image: node:20
  stage: unit_test
  script:
    - npm ci
    - npm run test

update_helm_chart:
  stage: update_helm_chart
  image: ubuntu:22.04
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"
    - mkdir -p /root/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - git config --global user.email "hammouche55@gmail.com"
    - git config --global user.name "devdevrl"
    - git clone git@gitlab.com:dev1423212/am-manifests.git
    - cd am-manifests
  script:
    - sed -i "s|webcongress-test-delivery:.*|webcongress-test-delivery:${CI_COMMIT_SHORT_SHA}|g" webcongress-test-delivery/values.yaml
    - git add webcongress-test-delivery/values.yaml
    - git commit -am "Update Image"
    - git push
