apiVersion: v1
kind: Service
metadata:
  labels:
    app: awebcongress-test-delivery-svc
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - name: webcongress-test-delivery-svc
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: webcongress-test-delivery
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}